name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "REPLACE"
          replace: "${{ secrets.CONNECTIONSTRING }}"
          
  build:
    runs-on: ubuntu-latest
    needs: replace
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
        connectionstring: ${{ secrets.CONNECTIONSTRING }}
    - name: Test
      run: dotnet test --no-restore
